IF DB_ID ('BD_SITTPR') IS NOT NULL
BEGIN
	DROP DATABASE BD_SITTPR
END
GO 

CREATE DATABASE BD_SITTPR
GO

USE BD_SITTPR
GO

CREATE SCHEMA AUTHORIZATION Sittpr
GO

CREATE TABLE PAIS (
		CODIGO CHAR(5) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL
	)
GO

CREATE TABLE PROVEEDOR (
		CODIGO CHAR(10) NOT NULL,
		RUC VARCHAR(50) NOT NULL,
		RAZSOCIAL VARCHAR(50) NOT NULL,
		REPLEGAL VARCHAR(50) NOT NULL,
		DIRECCION VARCHAR(50) NOT NULL,
		TELEFONO VARCHAR(50) NOT NULL,
		CORREO VARCHAR(50) NOT NULL,
		FECHAREG VARCHAR(50) NULL,
		FECHAACT VARCHAR(50) NULL,
		CTABANCARIA VARCHAR(50) NOT NULL,
		PAISCODIGO CHAR(5) NOT NULL
	)
GO

CREATE TABLE MOBILIARIO (
		CODIGO CHAR(10) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL,
		CANTIDAD INTEGER NOT NULL,
		FECHAREG VARCHAR(50) NULL,
		FECHAACT VARCHAR(50) NULL,
		PROVEEDORCODIGO CHAR(10) NOT NULL,
		TIPOEQMOBCODIGO CHAR(5) NOT NULL,
		ESTADOMOBEQUIPCODIGO CHAR(5) NOT NULL,
		ESTACIÓNCODIGO CHAR(5) NOT NULL
	)
GO

CREATE TABLE EQUIPO (
		CODIGO CHAR(10) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL,
		PLACA VARCHAR(50) NOT NULL,
		FECHAREG VARCHAR(50) NULL,
		FECHAACT VARCHAR(50) NULL,
		PROVEEDORCODIGO CHAR(10) NOT NULL,
		TIPOEQMOBCODIGO CHAR(5) NOT NULL,
		ESTADOMOBEQUIPCODIGO CHAR(5) NOT NULL
	)
GO

CREATE TABLE TIPOEQMOB (
		CODIGO CHAR(5) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL
	)
GO

CREATE TABLE ESTADOMOBEQUIP (
		CODIGO CHAR(5) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL
	)
GO

CREATE TABLE CAMBIO (
		CODIGO CHAR(10) NOT NULL,
		ESTADO VARCHAR(50) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL,
		FECHAREG VARCHAR(50) NOT NULL,
		EMPLEADOCODIGO CHAR(10) NOT NULL
	)
GO

CREATE TABLE MANTENIMIENTO (
		CODIGO CHAR(10) NOT NULL,
		ESTADO VARCHAR(50) NULL,
		DESCRIPCION VARCHAR(50) NULL,
		FECHAREG VARCHAR(50) NULL,
		EMPLEADOCODIGO CHAR(10) NOT NULL
	)
GO

CREATE TABLE RECLAMO (
		CODIGO CHAR(10) NOT NULL,
		DNIUSUARIO VARCHAR(50) NOT NULL,
		NOMBREUSUARIO VARCHAR(50) NOT NULL,
		APELLIDOSUSUARIO VARCHAR(50) NOT NULL,
		TIPOUSUARIO VARCHAR(50) NOT NULL,
		FECHAREG VARCHAR(50) NOT NULL,
		ESTADO VARCHAR(50) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL,
		USUARIOCODIGO CHAR(10) NOT NULL,
		ESTACIÓNCODIGO CHAR(5) NOT NULL,
		EMPLEADOCODIGO CHAR(10) NOT NULL
	)
GO

CREATE TABLE TRANSBORDOS (
		CANTIDAD INTEGER NOT NULL,
		HORA VARCHAR(50) NULL,
		CODIGO CHAR(10) NOT NULL,
		COBRANZACODIGO CHAR(10) NOT NULL
	)
GO

CREATE TABLE USUARIO (
		CODIGO CHAR(10) NOT NULL,
		DNI VARCHAR(50) NOT NULL,
		NOMBRE VARCHAR(50) NOT NULL,
		APELLIDOS VARCHAR(50) NOT NULL,
		SEXO VARCHAR(50) NOT NULL,
		EDAD INTEGER NOT NULL,
		NACIONALIDAD VARCHAR(50) NOT NULL,
		USUARIO VARCHAR(50) NOT NULL,
		CONTRASEÑA VARCHAR(50) NOT NULL,
		SALDO DECIMAL(10,2) PRECISION NOT NULL,
		FECHAREG VARCHAR(50) NULL,
		FECHAACT VARCHAR(50) NULL,
		TIPOUSUARIOCODIGO CHAR(5) NOT NULL,
		ESTADOEMPUSUCODIGO CHAR(5) NOT NULL,
		HUELLA IMAGE NULL
	)
GO

CREATE TABLE DETEQCAMBIO (
		NOMBREEQUIPO VARCHAR(50) NOT NULL,
		TIPOEQUIPO VARCHAR(50) NOT NULL,
		PLACAEQUIPO VARCHAR(50) NOT NULL,
		CODIGO CHAR(10) NOT NULL,
		CAMBIOCODIGO CHAR(10) NOT NULL
	)
GO

CREATE TABLE DETMOBCAMBIO (
		NOMBREMOB VARCHAR(50) NOT NULL,
		TIPOMOB VARCHAR(50) NOT NULL,
		ESTACIONMOB VARCHAR(50) NOT NULL,
		CODIGO CHAR(10) NOT NULL,
		CAMBIOCODIGO CHAR(10) NOT NULL
	)
GO

CREATE TABLE DETEQMANTENIMIENTO (
		NOMBREEQUIPO VARCHAR(50) NULL,
		TIPOEQUIPO VARCHAR(50) NULL,
		PLACAEQUIPO VARCHAR(50) NULL,
		CODIGO CHAR(10) NOT NULL,
		MANTENIMIENTOCODIGO CHAR(10) NOT NULL
	)
GO

CREATE TABLE DETMOBMANTENIMIENTO (
		NOMBREMOB VARCHAR(50) NULL,
		TIPOMOB VARCHAR(50) NULL,
		ESTACIONMOB VARCHAR(50) NULL,
		CODIGO CHAR(10) NOT NULL,
		MANTENIMIENTOCODIGO CHAR(10) NOT NULL
	)
GO

CREATE TABLE EMPLEADO (
		CODIGO CHAR(10) NOT NULL,
		DNI VARCHAR(50) NOT NULL,
		NOMBRE VARCHAR(50) NOT NULL,
		APELLIDOS VARCHAR(50) NOT NULL,
		SEXO VARCHAR(50) NOT NULL,
		CORREO VARCHAR(50) NOT NULL,
		EDAD INTEGER NOT NULL,
		DIRECCION VARCHAR(50) NOT NULL,
		TELEFONO VARCHAR(50) NOT NULL,
		USUARIO VARCHAR(50) NOT NULL,
		CONTRASEÑA VARCHAR(50) NOT NULL,
		FECHAREG VARCHAR(50) NULL,
		FECHAACT VARCHAR(50) NULL,
		TIPOEMPLEADOCODIGO CHAR(5) NOT NULL,
		ESTADOEMPUSUCODIGO CHAR(5) NOT NULL,
		ESTACIÓNCODIGO CHAR(5) NOT NULL,
		AREACODIGO CHAR(5) NOT NULL
	)
GO

CREATE TABLE RECARGA (
		CODIGO CHAR(10) NOT NULL,
		MONTO DECIMAL(10,2) PRECISION NOT NULL,
		FECHAREG VARCHAR(50) NOT NULL,
		DNI VARCHAR(50) NOT NULL,
		USUARIOCODIGO CHAR(10) NOT NULL
	)
GO

CREATE TABLE RUTA (
		CODIGO CHAR(10) NOT NULL,
		FECHAREG VARCHAR(50) NULL,
		TURNO VARCHAR(50) NOT NULL,
		PLACA VARCHAR(50) NOT NULL,
		HORAPARTIDA VARCHAR(50) NULL,
		TIPORUTACODIGO CHAR(5) NOT NULL,
		EMPLEADOCODIGO CHAR(10) NOT NULL,
		EQUIPOCODIGO CHAR(10) NOT NULL
	)
GO

CREATE TABLE COBRANZA (
		CODIGO CHAR(10) NOT NULL,
		CANTIDAD INTEGER NOT NULL,
		FECHAREG VARCHAR(50) NULL,
		MONTO DECIMAL(10,2) PRECISION NOT NULL,
		TIPOSERVICIOCODIGO CHAR(5) NOT NULL
	)
GO

CREATE TABLE TIPOSERVICIO (
		CODIGO CHAR(5) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL
	)
GO

CREATE TABLE ESTADOEMPUSU (
		CODIGO CHAR(5) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL
	)
GO

CREATE TABLE ESTACIÓN (
		CODIGO CHAR(5) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL
	)
GO

CREATE TABLE AREA (
		CODIGO CHAR(5) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL
	)
GO

CREATE TABLE TIPOEMPLEADO (
		CODIGO CHAR(5) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL
	)
GO

CREATE TABLE TIPOUSUARIO (
		CODIGO CHAR(5) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL
	)
GO

CREATE TABLE TIPORUTA (
		CODIGO CHAR(5) NOT NULL,
		DESCRIPCION VARCHAR(50) NOT NULL
	)
GO

ALTER TABLE PAIS ADD CONSTRAINT PAIS_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE PROVEEDOR ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE MOBILIARIO ADD CONSTRAINT MOBILIARIO_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE EQUIPO ADD CONSTRAINT EQUIPO_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE TIPOEQMOB ADD CONSTRAINT TIPOEQMOB_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE ESTADOMOBEQUIP ADD CONSTRAINT ESTADOMOBEQUIP_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE CAMBIO ADD CONSTRAINT CAMBIO_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE MANTENIMIENTO ADD CONSTRAINT MANTENIMIENTO_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE RECLAMO ADD CONSTRAINT RECLAMO_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE TRANSBORDOS ADD CONSTRAINT TRANSBORDOS_PK PRIMARY KEY
	(COBRANZACODIGO,
	 CODIGO)
GO

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE DETEQCAMBIO ADD CONSTRAINT DETEQCAMBIO_PK PRIMARY KEY
	(CAMBIOCODIGO,
	 CODIGO)
GO

ALTER TABLE DETMOBCAMBIO ADD CONSTRAINT DETMOBCAMBIO_PK PRIMARY KEY
	(CAMBIOCODIGO,
	 CODIGO)
GO

ALTER TABLE DETEQMANTENIMIENTO ADD CONSTRAINT DETEQMANTENIMIENTO_PK PRIMARY KEY
	(MANTENIMIENTOCODIGO,
	 CODIGO)
GO

ALTER TABLE DETMOBMANTENIMIENTO ADD CONSTRAINT DETMOBMANTENIMIENTO_PK PRIMARY KEY
	(MANTENIMIENTOCODIGO,
	 CODIGO)
GO

ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE RECARGA ADD CONSTRAINT RECARGA_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE RUTA ADD CONSTRAINT RUTA_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE COBRANZA ADD CONSTRAINT COBRANZA_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE TIPOSERVICIO ADD CONSTRAINT TIPOSERVICIO_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE ESTADOEMPUSU ADD CONSTRAINT ESTADOEMPUSU_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE ESTACIÓN ADD CONSTRAINT ESTACIÓN_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE AREA ADD CONSTRAINT AREA_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE TIPOEMPLEADO ADD CONSTRAINT TIPOEMPLEADO_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE TIPOUSUARIO ADD CONSTRAINT TIPOUSUARIO_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE TIPORUTA ADD CONSTRAINT TIPORUTA_PK PRIMARY KEY
	(CODIGO)
GO

ALTER TABLE PROVEEDOR ADD CONSTRAINT PROVEEDOR_PAIS_FK FOREIGN KEY
	(PAISCODIGO)
	REFERENCES PAIS
	(CODIGO)
GO

ALTER TABLE MOBILIARIO ADD CONSTRAINT MOBILIARIO_PROVEEDOR_FK FOREIGN KEY
	(PROVEEDORCODIGO)
	REFERENCES PROVEEDOR
	(CODIGO)
GO

ALTER TABLE MOBILIARIO ADD CONSTRAINT MOBILIARIO_TIPOEQMOB_FK FOREIGN KEY
	(TIPOEQMOBCODIGO)
	REFERENCES TIPOEQMOB
	(CODIGO)
GO

ALTER TABLE MOBILIARIO ADD CONSTRAINT MOBILIARIO_ESTADOMOBEQUIP_FK FOREIGN KEY
	(ESTADOMOBEQUIPCODIGO)
	REFERENCES ESTADOMOBEQUIP
	(CODIGO)
GO

ALTER TABLE MOBILIARIO ADD CONSTRAINT MOBILIARIO_ESTACIÓN_FK FOREIGN KEY
	(ESTACIÓNCODIGO)
	REFERENCES ESTACIÓN
	(CODIGO)
GO

ALTER TABLE EQUIPO ADD CONSTRAINT EQUIPO_PROVEEDOR_FK FOREIGN KEY
	(PROVEEDORCODIGO)
	REFERENCES PROVEEDOR
	(CODIGO)
GO

ALTER TABLE EQUIPO ADD CONSTRAINT EQUIPO_TIPOEQMOB_FK FOREIGN KEY
	(TIPOEQMOBCODIGO)
	REFERENCES TIPOEQMOB
	(CODIGO)
GO

ALTER TABLE EQUIPO ADD CONSTRAINT EQUIPO_ESTADOMOBEQUIP_FK FOREIGN KEY
	(ESTADOMOBEQUIPCODIGO)
	REFERENCES ESTADOMOBEQUIP
	(CODIGO)
GO

ALTER TABLE CAMBIO ADD CONSTRAINT CAMBIO_EMPLEADO_FK FOREIGN KEY
	(EMPLEADOCODIGO)
	REFERENCES EMPLEADO
	(CODIGO)
GO

ALTER TABLE MANTENIMIENTO ADD CONSTRAINT MANTENIMIENTO_EMPLEADO_FK FOREIGN KEY
	(EMPLEADOCODIGO)
	REFERENCES EMPLEADO
	(CODIGO)
GO

ALTER TABLE RECLAMO ADD CONSTRAINT RECLAMO_USUARIO_FK FOREIGN KEY
	(USUARIOCODIGO)
	REFERENCES USUARIO
	(CODIGO)
GO

ALTER TABLE RECLAMO ADD CONSTRAINT RECLAMO_ESTACIÓN_FK FOREIGN KEY
	(ESTACIÓNCODIGO)
	REFERENCES ESTACIÓN
	(CODIGO)
GO

ALTER TABLE RECLAMO ADD CONSTRAINT RECLAMO_EMPLEADO_FK FOREIGN KEY
	(EMPLEADOCODIGO)
	REFERENCES EMPLEADO
	(CODIGO)
GO

ALTER TABLE TRANSBORDOS ADD CONSTRAINT TRANSBORDOS_USUARIO_FK FOREIGN KEY
	(CODIGO)
	REFERENCES USUARIO
	(CODIGO)
GO

ALTER TABLE TRANSBORDOS ADD CONSTRAINT TRANSBORDOS_COBRANZA_FK FOREIGN KEY
	(COBRANZACODIGO)
	REFERENCES COBRANZA
	(CODIGO)
GO

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_TIPOUSUARIO_FK FOREIGN KEY
	(TIPOUSUARIOCODIGO)
	REFERENCES TIPOUSUARIO
	(CODIGO)
GO

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_ESTADOEMPUSU_FK FOREIGN KEY
	(ESTADOEMPUSUCODIGO)
	REFERENCES ESTADOEMPUSU
	(CODIGO)
GO

ALTER TABLE DETEQCAMBIO ADD CONSTRAINT DETEQCAMBIO_EQUIPO_FK FOREIGN KEY
	(CODIGO)
	REFERENCES EQUIPO
	(CODIGO)
GO

ALTER TABLE DETEQCAMBIO ADD CONSTRAINT DETEQCAMBIO_CAMBIO_FK FOREIGN KEY
	(CAMBIOCODIGO)
	REFERENCES CAMBIO
	(CODIGO)
GO

ALTER TABLE DETMOBCAMBIO ADD CONSTRAINT DETMOBCAMBIO_MOBILIARIO_FK FOREIGN KEY
	(CODIGO)
	REFERENCES MOBILIARIO
	(CODIGO)
GO

ALTER TABLE DETMOBCAMBIO ADD CONSTRAINT DETMOBCAMBIO_CAMBIO_FK FOREIGN KEY
	(CAMBIOCODIGO)
	REFERENCES CAMBIO
	(CODIGO)
GO

ALTER TABLE DETEQMANTENIMIENTO ADD CONSTRAINT DETEQMANTENIMIENTO_EQUIPO_FK FOREIGN KEY
	(CODIGO)
	REFERENCES EQUIPO
	(CODIGO)
GO

ALTER TABLE DETEQMANTENIMIENTO ADD CONSTRAINT DETEQMANTENIMIENTO_MANTENIMIENTO_FK FOREIGN KEY
	(MANTENIMIENTOCODIGO)
	REFERENCES MANTENIMIENTO
	(CODIGO)
GO

ALTER TABLE DETMOBMANTENIMIENTO ADD CONSTRAINT DETMOBMANTENIMIENTO_MOBILIARIO_FK FOREIGN KEY
	(CODIGO)
	REFERENCES MOBILIARIO
	(CODIGO)
GO

ALTER TABLE DETMOBMANTENIMIENTO ADD CONSTRAINT DETMOBMANTENIMIENTO_MANTENIMIENTO_FK FOREIGN KEY
	(MANTENIMIENTOCODIGO)
	REFERENCES MANTENIMIENTO
	(CODIGO)
GO

ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_TIPOEMPLEADO_FK FOREIGN KEY
	(TIPOEMPLEADOCODIGO)
	REFERENCES TIPOEMPLEADO
	(CODIGO)
GO

ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_ESTADOEMPUSU_FK FOREIGN KEY
	(ESTADOEMPUSUCODIGO)
	REFERENCES ESTADOEMPUSU
	(CODIGO)
GO

ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_ESTACIÓN_FK FOREIGN KEY
	(ESTACIÓNCODIGO)
	REFERENCES ESTACIÓN
	(CODIGO)
GO

ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_AREA_FK FOREIGN KEY
	(AREACODIGO)
	REFERENCES AREA
	(CODIGO)
GO

ALTER TABLE RECARGA ADD CONSTRAINT RECARGA_USUARIO_FK FOREIGN KEY
	(USUARIOCODIGO)
	REFERENCES USUARIO
	(CODIGO)
GO

ALTER TABLE RUTA ADD CONSTRAINT RUTA_TIPORUTA_FK FOREIGN KEY
	(TIPORUTACODIGO)
	REFERENCES TIPORUTA
	(CODIGO)
GO

ALTER TABLE RUTA ADD CONSTRAINT RUTA_EMPLEADO_FK FOREIGN KEY
	(EMPLEADOCODIGO)
	REFERENCES EMPLEADO
	(CODIGO)
GO

ALTER TABLE RUTA ADD CONSTRAINT RUTA_EQUIPO_FK FOREIGN KEY
	(EQUIPOCODIGO)
	REFERENCES EQUIPO
	(CODIGO)
GO

ALTER TABLE COBRANZA ADD CONSTRAINT COBRANZA_TIPOSERVICIO_FK FOREIGN KEY
	(TIPOSERVICIOCODIGO)
	REFERENCES TIPOSERVICIO
	(CODIGO)
GO
